Make firewall check independent from HEALTH_CHECK_INTERVAL

diff --git a/rootfs/etc/services.d/healthcheck/run b/rootfs/etc/services.d/healthcheck/run
--- a/rootfs/etc/services.d/healthcheck/run
+++ b/rootfs/etc/services.d/healthcheck/run
@@ -29,22 +29,26 @@ echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] qBittorrent started with PID $qbittorr
 
 ## Run
 
-while :; do
-    if [[ $VPN_ENABLED != "no" ]]; then
-        # Check if it is possible to bypass the VPN
-        if (ping -I "$DOCKER_INTERFACE" -c 1 "$HEALTH_CHECK_HOST" > /dev/null 2>&1) || (ping -I "$DOCKER_INTERFACE" -c 1 "8.8.8.8" > /dev/null 2>&1); then
-            echo "$(date +'%Y-%m-%d %H:%M:%S') [ERROR] Firewall is down! Killing qBittorrent!"
-            s6-svc -k -d /var/run/s6/services/qbittorrent/
-            killall qbittorrent-nox
+if [[ $VPN_ENABLED != "no" ]]; then
+    ( while :; do
+        if [[ $VPN_ENABLED != "no" ]]; then
+            # Check if it is possible to bypass the VPN
+            if (ping -I "$DOCKER_INTERFACE" -c 1 "$HEALTH_CHECK_HOST" > /dev/null 2>&1) || (ping -I "$DOCKER_INTERFACE" -c 1 "8.8.8.8" > /dev/null 2>&1); then
+                echo "$(date +'%Y-%m-%d %H:%M:%S') [ERROR] Firewall is down! Killing qBittorrent!"
+                s6-svc -k -d /var/run/s6/services/qbittorrent/
+                killall qbittorrent-nox
 
-            # Not required but we have nothing better to do now
-            while :; do
-                killall qbittorrent-nox >/dev/null 2>&1
-                sleep 1
-            done
+                # Not required but we have nothing better to do now
+                while :; do
+                    killall qbittorrent-nox >/dev/null 2>&1
+                    sleep 1
+                done
+            fi
         fi
-    fi
+    done ) &
+fi
 
+while :; do
     # Check if HEALTH_CHECK_HOST is reachable
     start_time=$(date +%s)
     if ! (ping -c 1 "$HEALTH_CHECK_HOST" > /dev/null 2>&1); then
