Merge dev into master (#10)
* Randomly choose VPN config file

* Update README.md

* Fix export

* Update OpenVPN credential handling

* Log info before restarting the container

* Improve Firewall

diff --git a/rootfs/etc/cont-init.d/02-vpn b/rootfs/etc/cont-init.d/02-vpn
--- a/rootfs/etc/cont-init.d/02-vpn
+++ b/rootfs/etc/cont-init.d/02-vpn
@@ -14,6 +14,25 @@ fi
 # Create config dir (if it doesn't exist)
 mkdir -p "/config/${VPN_TYPE}"
 
+# Wildcard search for openvpn config files and store results in array
+if [[ "${VPN_TYPE}" == "openvpn" ]]; then
+    mapfile -t VPN_CONFIGS < <( find /config/openvpn -maxdepth 1 -name "*.ovpn" -print )
+else
+    mapfile -t VPN_CONFIGS < <( find /config/wireguard -maxdepth 1 -name "*.conf" -print )
+fi
+
+# Choose random config
+VPN_CONFIG="${VPN_CONFIGS[$RANDOM % ${#VPN_CONFIGS[@]}]}"
+
+# Get the VPN_CONFIG name without the path and extension
+VPN_CONFIG_BASENAME="${VPN_CONFIG##*/}"
+VPN_CONFIG_NAME="${VPN_CONFIG_BASENAME%.*}"
+
+echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] Choosen VPN config: '${VPN_CONFIG_BASENAME}'"
+
+export VPN_CONFIG
+export VPN_CONFIG_NAME
+
 # If VPN config file not found in /config/openvpn or /config/wireguard then exit
 if [[ -z ${VPN_CONFIG} ]]; then
     if [[ ${VPN_TYPE} == "openvpn" ]]; then
@@ -26,36 +45,35 @@ if [[ -z ${VPN_CONFIG} ]]; then
     exit 1
 fi
 
-if [[ ${VPN_TYPE} == "openvpn" ]]; then
-    echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] OpenVPN config file is found at ${VPN_CONFIG}"
-else
-    echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] WireGuard config file is found at ${VPN_CONFIG}"
-    if [[ ${VPN_CONFIG} != "/config/wireguard/wg0.conf" ]]; then
-        echo "$(date +'%Y-%m-%d %H:%M:%S') [ERROR] WireGuard config filename is not 'wg0.conf'"
-        echo "$(date +'%Y-%m-%d %H:%M:%S') [ERROR] Rename ${VPN_CONFIG} to 'wg0.conf'"
-        sleep 5
-        exit 1
-    fi
-fi
-
 ##########
 # OpenVPN credentails
 
 # Read username and password env vars and put them in credentials.conf, then add ovpn config for credentials file
 if [[ "${VPN_TYPE}" == "openvpn" ]]; then
     # Replace line with one that points to credentials.conf
-        auth_cred_exist=$(grep -m 1 'auth-user-pass' < "${VPN_CONFIG}")
-        if [[ -n "${auth_cred_exist}" ]]; then
-            # Get line number of auth-user-pass
-            LINE_NUM=$(grep -Fn -m 1 'auth-user-pass' "${VPN_CONFIG}" | cut -d: -f 1)
-            sed -i "${LINE_NUM}s/.*/auth-user-pass credentials.conf/" "${VPN_CONFIG}"
-        else
-            sed -i "1s/.*/auth-user-pass credentials.conf/" "${VPN_CONFIG}"
-        fi
+    auth_cred_exist=$(grep -m 1 'auth-user-pass' < "${VPN_CONFIG}")
+    if [[ -n "${auth_cred_exist}" ]]; then
+        # Get line number of auth-user-pass
+        LINE_NUM=$(grep -Fn -m 1 'auth-user-pass' "${VPN_CONFIG}" | cut -d: -f 1)
+        sed -i "${LINE_NUM}s/.*/auth-user-pass ${VPN_CONFIG_NAME}_credentials.conf/" "${VPN_CONFIG}"
+    else
+        sed -i "1s/.*/auth-user-pass ${VPN_CONFIG_NAME}_credentials.conf/" "${VPN_CONFIG}"
+    fi
 
-    if [[ -n "${VPN_USERNAME}" ]] && [[ -n "${VPN_PASSWORD}" ]]; then
-        echo "${VPN_USERNAME}" > /config/openvpn/credentials.conf
-        echo "${VPN_PASSWORD}" >> /config/openvpn/credentials.conf
+    if [[ -f /config/openvpn/"${VPN_CONFIG_NAME}"_credentials.conf ]]; then
+        echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] Using credentials from /config/openvpn/${VPN_CONFIG_NAME}_credentials.conf"
+    elif [[ -n "${VPN_USERNAME}" ]] && [[ -n "${VPN_PASSWORD}" ]]; then
+        echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] Using credentials from env vars"
+        echo "${VPN_USERNAME}" > /config/openvpn/"${VPN_CONFIG_NAME}"_credentials.conf
+        echo "${VPN_PASSWORD}" >> /config/openvpn/"${VPN_CONFIG_NAME}"_credentials.conf
+    elif [[ -f /config/openvpn/credentials.conf ]]; then
+        echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] Copying credentials from /config/openvpn/credentials.conf to /config/openvpn/${VPN_CONFIG_NAME}_credentials.conf"
+        cp /config/openvpn/credentials.conf /config/openvpn/"${VPN_CONFIG_NAME}"_credentials.conf
+    else
+        echo "$(date +'%Y-%m-%d %H:%M:%S') [ERROR] No credentials set and didn't find a credential config file."
+        # Sleep so it wont 'spam restart'
+        sleep 5
+        exit 1
     fi
 fi
 
@@ -147,8 +165,8 @@ if [[ "${VPN_TYPE}" == "openvpn" ]]; then
         exit 1
     fi
 else
-    export VPN_DEVICE_TYPE="wg0"
-    echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] VPN_DEVICE_TYPE set as '${VPN_DEVICE_TYPE}', since WireGuard will always be wg0."
+    export VPN_DEVICE_TYPE="$VPN_CONFIG_NAME"
+    echo "$(date +'%Y-%m-%d %H:%M:%S') [INFO] VPN_DEVICE_TYPE set as '${VPN_DEVICE_TYPE}'"
 fi
 
 ##########
@@ -212,7 +230,7 @@ set +e
 
 CONT_INIT_ENV="/var/run/s6/container_environment"
 mkdir -p $CONT_INIT_ENV
-export_vars=("VPN_REMOTE" "VPN_PORT" "VPN_PROTOCOL" "VPN_DEVICE_TYPE")
+export_vars=("VPN_REMOTE" "VPN_PORT" "VPN_PROTOCOL" "VPN_DEVICE_TYPE" "VPN_CONFIG_NAME")
 
 for name in "${export_vars[@]}"; do
 	echo -n "${!name}" > "$CONT_INIT_ENV/$name"
